spring:
  application:
    name: simple-ticket-management-backend
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:15211:xe
    username: ticket_mngt_db
    password: 1234
  jpa:
    database-platform: org.hibernate.community.dialect.Oracle12cDialect
